# Generated by Django 4.2.3 on 2023-07-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='expression',
        ),
        migrations.AddField(
            model_name='calculation',
            name='input_one',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculation',
            name='input_two',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculation',
            name='operand',
            field=models.CharField(default=0.0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculation',
            name='result',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
